"""Skills / competency registry (PRD C8) + role matrices (D23) + D08 import."""

from app.modules.skills.framework import (
    approve_framework_import,
    approve_to_proposal,
    create_framework_import,
    list_framework_imports,
    list_to_proposals,
    normalize_spec,
    parse_framework_csv,
    parse_framework_json,
    reject_to_proposal,
)
from app.modules.skills.service import (
    add_role_skill,
    bind_default_lesson,
    bind_default_manual,
    competency_catalog,
    create_role_profile,
    create_skill,
    ensure_default_roles,
    ensure_default_skills,
    link_question_to_skill,
    list_role_profiles,
    list_skills,
    remediation_for_question,
    required_skills_for_role,
    set_role_skills,
    set_skill_remediation,
    skill_gaps_for_role,
    skill_map_by_question,
    upsert_skill_pack,
)

__all__ = [
    "list_skills",
    "ensure_default_skills",
    "upsert_skill_pack",
    "create_skill",
    "link_question_to_skill",
    "set_skill_remediation",
    "skill_map_by_question",
    "remediation_for_question",
    "competency_catalog",
    "bind_default_manual",
    "bind_default_lesson",
    "list_role_profiles",
    "create_role_profile",
    "set_role_skills",
    "add_role_skill",
    "ensure_default_roles",
    "required_skills_for_role",
    "skill_gaps_for_role",
    "parse_framework_json",
    "parse_framework_csv",
    "normalize_spec",
    "create_framework_import",
    "list_framework_imports",
    "approve_framework_import",
    "list_to_proposals",
    "approve_to_proposal",
    "reject_to_proposal",
]
