#!/usr/bin/env python3
"""Automate EdVidura Railway secrets + (optional) CLI project wiring.

Dry-run (default):
  python scripts/railway_bootstrap.py

Create project, add Postgres, set vars, generate domain, deploy:
  python scripts/railway_bootstrap.py --apply

Requires Railway CLI for --apply:
  npm i -g @railway/cli
  railway login
"""
from __future__ import annotations

import argparse
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEYS = ROOT / "keys"
ENV_OUT = KEYS / "railway-bootstrap.env"
PRIVATE_KEY = KEYS / "private.key"


def _run(args: list[str], *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args,
        cwd=ROOT,
        check=check,
        text=True,
        capture_output=capture,
    )


def _railway(*args: str, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    exe = shutil.which("railway")
    if not exe:
        print("Railway CLI not found. Install: npm i -g @railway/cli", file=sys.stderr)
        sys.exit(2)
    return _run([exe, *args], check=check, capture=capture)


def _ensure_lti_key() -> str:
    KEYS.mkdir(parents=True, exist_ok=True)
    if not PRIVATE_KEY.exists() or PRIVATE_KEY.stat().st_size < 80:
        _run([sys.executable, str(ROOT / "scripts" / "generate_keys.py")])
    pem = PRIVATE_KEY.read_text(encoding="utf-8").strip()
    return pem.replace("\r\n", "\n")


def _load_or_make_secrets() -> dict[str, str]:
    existing: dict[str, str] = {}
    if ENV_OUT.exists():
        for line in ENV_OUT.read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()

    session = existing.get("SESSION_SECRET") or secrets.token_urlsafe(32)
    admin = existing.get("ADMIN_API_KEY") or secrets.token_urlsafe(24)
    pem = existing.get("LTI_PRIVATE_KEY_PEM") or _ensure_lti_key().replace("\n", "\\n")
    return {
        "ENVIRONMENT": "production",
        "SESSION_SECRET": session,
        "ADMIN_API_KEY": admin,
        "LTI_PRIVATE_KEY_PEM": pem,
        "RUN_MIGRATIONS": "1",
        "APP_BASE_URL": existing.get("APP_BASE_URL", "https://REPLACE-ME.up.railway.app"),
    }


def _write_env(vals: dict[str, str]) -> None:
    KEYS.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/railway_bootstrap.py — do not commit",
        f"ENVIRONMENT={vals['ENVIRONMENT']}",
        f"SESSION_SECRET={vals['SESSION_SECRET']}",
        f"ADMIN_API_KEY={vals['ADMIN_API_KEY']}",
        f"APP_BASE_URL={vals['APP_BASE_URL']}",
        f"RUN_MIGRATIONS={vals['RUN_MIGRATIONS']}",
        f"LTI_PRIVATE_KEY_PEM={vals['LTI_PRIVATE_KEY_PEM']}",
        "",
    ]
    ENV_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {ENV_OUT.relative_to(ROOT)}")


def _print_manual(vals: dict[str, str]) -> None:
    print()
    print("Railway dashboard → web service → Variables:")
    print(f"  ENVIRONMENT={vals['ENVIRONMENT']}")
    print(f"  SESSION_SECRET={vals['SESSION_SECRET']}")
    print(f"  ADMIN_API_KEY={vals['ADMIN_API_KEY']}")
    print(f"  APP_BASE_URL={vals['APP_BASE_URL']}")
    print("  RUN_MIGRATIONS=1   (first boot only, then 0)")
    print("  LTI_PRIVATE_KEY_PEM=<from keys/railway-bootstrap.env>")
    print("  DATABASE_URL       (from Railway Postgres plugin)")
    print()
    print("After the public domain exists, set APP_BASE_URL to https://<domain> (no slash).")
    print("Moodle tool URLs:")
    print("  {APP_BASE_URL}/lti/launch")
    print("  {APP_BASE_URL}/lti/login")
    print("  {APP_BASE_URL}/.well-known/jwks.json")


def _set_vars(vals: dict[str, str]) -> None:
    for key in (
        "ENVIRONMENT",
        "SESSION_SECRET",
        "ADMIN_API_KEY",
        "APP_BASE_URL",
        "RUN_MIGRATIONS",
        "LTI_PRIVATE_KEY_PEM",
    ):
        print(f"Setting {key}…")
        _railway("variable", "set", f"{key}={vals[key]}")


def _detect_domain() -> str | None:
    proc = _railway("domain", check=False, capture=True)
    text = (proc.stdout or "") + "\n" + (proc.stderr or "")
    for token in text.replace("\n", " ").split():
        if token.startswith("https://"):
            return token.rstrip("/")
        if ".up.railway.app" in token or ".railway.app" in token:
            host = token.strip().strip("/")
            if not host.startswith("http"):
                host = "https://" + host
            return host.rstrip("/")
    return None


def _apply(vals: dict[str, str], *, skip_up: bool) -> dict[str, str]:
    who = _railway("whoami", check=False, capture=True)
    if who.returncode != 0:
        print("Not logged in. Run: railway login", file=sys.stderr)
        sys.exit(1)
    print((who.stdout or who.stderr or "").strip())

    status = _railway("status", check=False, capture=True)
    linked = status.returncode == 0 and "Project" in (status.stdout or "")
    if not linked:
        print("No linked project. Creating one (railway init)…")
        _railway("init", "--name", "edvidura")

    print("Ensuring Postgres…")
    add = _railway("add", "--database", "postgres", check=False, capture=True)
    if add.returncode != 0:
        msg = (add.stderr or add.stdout or "").lower()
        if "already" not in msg and "exist" not in msg:
            print(add.stderr or add.stdout or "railway add postgres failed", file=sys.stderr)

    print("Generating public domain (if missing)…")
    _railway("domain", check=False)
    domain = _detect_domain()
    if domain:
        vals["APP_BASE_URL"] = domain
        print(f"APP_BASE_URL={domain}")
    else:
        print("Could not parse domain yet — set APP_BASE_URL after Railway shows the URL.")

    _write_env(vals)
    _set_vars(vals)

    if skip_up:
        print("Skipped deploy (--skip-up). Run: railway up")
        return vals

    print("Deploying (railway up --detach)…")
    _railway("up", "--detach")
    print("Deploy started. Watch: railway logs")
    print("Health:  GET {APP_BASE_URL}/health")
    return vals


def main() -> None:
    p = argparse.ArgumentParser(description="Generate Railway secrets and optionally apply via CLI")
    p.add_argument("--apply", action="store_true", help="Create/link Railway project, set vars, deploy")
    p.add_argument("--skip-up", action="store_true", help="With --apply, set vars but do not railway up")
    args = p.parse_args()

    vals = _load_or_make_secrets()
    _write_env(vals)
    print(f"SESSION_SECRET / ADMIN_API_KEY / LTI key ready in {ENV_OUT.name}")

    if not args.apply:
        _print_manual(vals)
        print()
        print("To apply with the Railway CLI:")
        print("  npm i -g @railway/cli")
        print("  railway login")
        print("  python scripts/railway_bootstrap.py --apply")
        return

    vals = _apply(vals, skip_up=args.skip_up)
    _print_manual(vals)
    print()
    print("After first healthy deploy, set RUN_MIGRATIONS=0:")
    print("  railway variable set RUN_MIGRATIONS=0")


if __name__ == "__main__":
    main()
