"""C9 adaptive recommendations + C10 gap training + PLE plans + DCT order."""

from app.modules.adaptive.service import (
    apply_dynamic_lesson_order,
    build_difference_path,
    build_gap_path,
    complete_open_plan,
    dct_planner_pack,
    gap_path_from_latest_attempt,
    get_open_plan,
    href_with_token,
    href_without_token,
    hydrate_plan,
    latest_graded_attempt_for_subject,
    mark_plan_step_done,
    order_lessons_for_gaps,
    recommend_next_lesson,
    resolve_learner_plan,
    serialize_steps_for_storage,
    sync_plan_after_attempt,
    upsert_open_plan,
    weak_skill_codes_for_subject,
    weak_skills_from_attempt,
)

__all__ = [
    "weak_skills_from_attempt",
    "build_gap_path",
    "build_difference_path",
    "recommend_next_lesson",
    "gap_path_from_latest_attempt",
    "latest_graded_attempt_for_subject",
    "href_without_token",
    "href_with_token",
    "serialize_steps_for_storage",
    "hydrate_plan",
    "get_open_plan",
    "upsert_open_plan",
    "complete_open_plan",
    "mark_plan_step_done",
    "sync_plan_after_attempt",
    "resolve_learner_plan",
    "weak_skill_codes_for_subject",
    "order_lessons_for_gaps",
    "apply_dynamic_lesson_order",
    "dct_planner_pack",
]
